name: Build and execute Python Script
# pip freeze > requirements.txt

on : [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up Python 3.10.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.12

    - name: Install dependencies
      shell: bash
      run: |
        pip install fastapi locust uvicorn

    - name: Execution de pytest
      run: pytest